Este Notebook (incompleto) es un complemento del notrbook anterior de Ngrams. La idea es entrenar un modelo ngram utilizando los Google Ngrams. Como práctica estaría bueno que lo completen y lo corran end to end.

In [ ]:
!pip install google_ngram_downloader

import nltk
import random
from nltk.lm import Lidstone
from google_ngram_downloader  import readline_google_store
import re


nltk.download('punkt')

Collecting google_ngram_downloader
  Downloading google-ngram-downloader-4.0.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting opster (from google_ngram_downloader)
  Downloading opster-5.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting py (from google_ngram_downloader)
  Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from google_ngram_downloader) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->google_ngram_downloader) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->google_ngram_downloader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->google_ngram_downloader) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->google_ngram_downloader) (2023.7.22)
Building wheels for collected packages: google_ngram_downloader, opster
  Building wheel for google_ngram_downloader (setup.py) ... done
  Created wheel for google_ngram_downloader: filename=google_ngram_downloader-4.0.1-py3-none-any.whl size=8904 sha256=d37d651d07eec3fef6bcb945d19c9a7c33e090cc1336f232a93462833806c76a
  Stored in directory: /root/.cache/pip/wheels/23/28/bb/8cf7395afdaf603ef9d9e965f3d95daa84ae45375f6c2c61b5
  Building wheel for opster (setup.py) ... done
  Created wheel for opster: filename=opster-5.0-py3-none-any.whl size=11794 sha256=35bd65d7277c647b150956f62118b11310553386f559c8c3418cee90462e06c6
  Stored in directory: /root/.cache/pip/wheels/25/b9/f7/e2ad7b1f948611df0475224ad7be6dd8ee30af289af56b23d4
Successfully built google_ngram_downloader opster
Installing collected packages: opster, py, google_ngram_downloader
Successfully installed google_ngram_downloader-4.0.1 opster-5.0 py-1.11.0

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
def process_ngram(ngram):
    tokens = ngram.split()

    words = []

    for token in tokens:

        match = re.search(r"(.*)_(\w+)", token)
        if match:
            word = match.group(1)
            if word:
                words.append(word)
        else:
            words.append(token)

    words = [word.replace('_', '').lower() for word in words]
    words = ' '.join(words)
    words = nltk.word_tokenize(words)
    words = ' '.join(words)
    return words

In [ ]:
n = 1

v = 10000

In [ ]:
def fetch_ngrams(n, lang):
    try:
        fname, url, records = next(readline_google_store(ngram_len=n, lang=lang))
        return records
    except:
        print("Error fetching the n-grams.")
        return []

# Let's process only the first 10,000 n-grams for demonstration purposes
MAX_NGRAMS = None

ngram_freqs = []
``
processed = 0

for idx, record in enumerate(fetch_ngrams(n, 'spa')):
    if MAX_NGRAMS is not None and idx > MAX_NGRAMS:
        break
    ngram, year, freq, _ = record
    ngram = process_ngram(ngram)
    ngram_freqs.append((ngram, freq))
    processed += 1
    if processed % 50000 == 0:
        print('Ngrams processed', processed)

Streaming output truncated to the last 5000 lines.
Record(ngram='0,73_NUM', year=1879, match_count=10, volume_count=7)
Record(ngram='0,73_NUM', year=1880, match_count=3, volume_count=2)
Record(ngram='0,73_NUM', year=1881, match_count=4, volume_count=2)
Record(ngram='0,73_NUM', year=1882, match_count=9, volume_count=8)
Record(ngram='0,73_NUM', year=1883, match_count=6, volume_count=4)
Record(ngram='0,73_NUM', year=1884, match_count=2, volume_count=2)
Record(ngram='0,73_NUM', year=1885, match_count=1, volume_count=1)
Record(ngram='0,73_NUM', year=1886, match_count=1, volume_count=1)
Record(ngram='0,73_NUM', year=1887, match_count=3, volume_count=3)
Record(ngram='0,73_NUM', year=1888, match_count=10, volume_count=9)
Record(ngram='0,73_NUM', year=1889, match_count=4, volume_count=4)
Record(ngram='0,73_NUM', year=1890, match_count=7, volume_count=6)
Record(ngram='0,73_NUM', year=1891, match_count=1, volume_count=1)
Record(ngram='0,73_NUM', year=1892, match_count=7, volume_count=7)
Record(ngram='0,73_NUM', year=1893, match_count=4, volume_count=3)
Record(ngram='0,73_NUM', year=1894, match_count=13, volume_count=8)
Record(ngram='0,73_NUM', year=1895, match_count=8, volume_count=8)
Record(ngram='0,73_NUM', year=1896, match_count=7, volume_count=6)
Record(ngram='0,73_NUM', year=1897, match_count=1, volume_count=1)
Record(ngram='0,73_NUM', year=1898, match_count=5, volume_count=4)
Record(ngram='0,73_NUM', year=1899, match_count=8, volume_count=7)
Record(ngram='0,73_NUM', year=1900, match_count=13, volume_count=6)
Record(ngram='0,73_NUM', year=1901, match_count=13, volume_count=9)
Record(ngram='0,73_NUM', year=1902, match_count=2, volume_count=2)
Record(ngram='0,73_NUM', year=1903, match_count=18, volume_count=14)
Record(ngram='0,73_NUM', year=1904, match_count=4, volume_count=4)
Record(ngram='0,73_NUM', year=1905, match_count=15, volume_count=7)
Record(ngram='0,73_NUM', year=1906, match_count=9, volume_count=4)
Record(ngram='0,73_NUM', year=1907, match_count=17, volume_count=13)
Record(ngram='0,73_NUM', year=1908, match_count=21, volume_count=13)
Record(ngram='0,73_NUM', year=1909, match_count=7, volume_count=6)
Record(ngram='0,73_NUM', year=1910, match_count=15, volume_count=11)
Record(ngram='0,73_NUM', year=1911, match_count=12, volume_count=8)
Record(ngram='0,73_NUM', year=1912, match_count=34, volume_count=18)
Record(ngram='0,73_NUM', year=1913, match_count=11, volume_count=11)
Record(ngram='0,73_NUM', year=1914, match_count=13, volume_count=8)
Record(ngram='0,73_NUM', year=1915, match_count=15, volume_count=13)
Record(ngram='0,73_NUM', year=1916, match_count=26, volume_count=14)
Record(ngram='0,73_NUM', year=1917, match_count=18, volume_count=15)
Record(ngram='0,73_NUM', year=1918, match_count=18, volume_count=12)
Record(ngram='0,73_NUM', year=1919, match_count=19, volume_count=16)
Record(ngram='0,73_NUM', year=1920, match_count=31, volume_count=20)
Record(ngram='0,73_NUM', year=1921, match_count=20, volume_count=13)
Record(ngram='0,73_NUM', year=1922, match_count=19, volume_count=14)
Record(ngram='0,73_NUM', year=1923, match_count=18, volume_count=15)
Record(ngram='0,73_NUM', year=1924, match_count=13, volume_count=7)
Record(ngram='0,73_NUM', year=1925, match_count=43, volume_count=24)
Record(ngram='0,73_NUM', year=1926, match_count=80, volume_count=18)
Record(ngram='0,73_NUM', year=1927, match_count=166, volume_count=18)
Record(ngram='0,73_NUM', year=1928, match_count=63, volume_count=30)
Record(ngram='0,73_NUM', year=1929, match_count=37, volume_count=31)
Record(ngram='0,73_NUM', year=1930, match_count=31, volume_count=18)
Record(ngram='0,73_NUM', year=1931, match_count=20, volume_count=14)
Record(ngram='0,73_NUM', year=1932, match_count=69, volume_count=19)
Record(ngram='0,73_NUM', year=1933, match_count=65, volume_count=37)
Record(ngram='0,73_NUM', year=1934, match_count=76, volume_count=31)
Record(ngram='0,73_NUM', year=1935, match_count=41, volume_count=31)
Record(ngram='0,73_NUM', year=1936, match_count=22, volume_count=17)
Record(ngram='0,73_NUM', year=1937, match_count=42, volume_count=31)
Record(ngram='0,73_NUM', year=1938, match_count=26, volume_count=19)
Record(ngram='0,73_NUM', year=1939, match_count=27, volume_count=21)
Record(ngram='0,73_NUM', year=1940, match_count=99, volume_count=41)
Record(ngram='0,73_NUM', year=1941, match_count=117, volume_count=61)
Record(ngram='0,73_NUM', year=1942, match_count=58, volume_count=30)
Record(ngram='0,73_NUM', year=1943, match_count=65, volume_count=37)
Record(ngram='0,73_NUM', year=1944, match_count=113, volume_count=52)
Record(ngram='0,73_NUM', year=1945, match_count=87, volume_count=56)
Record(ngram='0,73_NUM', year=1946, match_count=78, volume_count=49)
Record(ngram='0,73_NUM', year=1947, match_count=67, volume_count=35)
Record(ngram='0,73_NUM', year=1948, match_count=86, volume_count=47)
Record(ngram='0,73_NUM', year=1949, match_count=95, volume_count=60)
Record(ngram='0,73_NUM', year=1950, match_count=63, volume_count=38)
Record(ngram='0,73_NUM', year=1951, match_count=73, volume_count=37)
Record(ngram='0,73_NUM', year=1952, match_count=60, volume_count=38)
Record(ngram='0,73_NUM', year=1953, match_count=59, volume_count=38)
Record(ngram='0,73_NUM', year=1954, match_count=75, volume_count=46)
Record(ngram='0,73_NUM', year=1955, match_count=90, volume_count=51)
Record(ngram='0,73_NUM', year=1956, match_count=84, volume_count=51)
Record(ngram='0,73_NUM', year=1957, match_count=71, volume_count=46)
Record(ngram='0,73_NUM', year=1958, match_count=121, volume_count=59)
Record(ngram='0,73_NUM', year=1959, match_count=85, volume_count=58)
Record(ngram='0,73_NUM', year=1960, match_count=144, volume_count=69)
Record(ngram='0,73_NUM', year=1961, match_count=148, volume_count=67)
Record(ngram='0,73_NUM', year=1962, match_count=158, volume_count=93)
Record(ngram='0,73_NUM', year=1963, match_count=197, volume_count=99)
Record(ngram='0,73_NUM', year=1964, match_count=204, volume_count=113)
Record(ngram='0,73_NUM', year=1965, match_count=174, volume_count=95)
Record(ngram='0,73_NUM', year=1966, match_count=245, volume_count=122)
Record(ngram='0,73_NUM', year=1967, match_count=222, volume_count=105)
Record(ngram='0,73_NUM', year=1968, match_count=166, volume_count=88)
Record(ngram='0,73_NUM', year=1969, match_count=242, volume_count=128)
Record(ngram='0,73_NUM', year=1970, match_count=270, volume_count=127)
Record(ngram='0,73_NUM', year=1971, match_count=230, volume_count=125)
Record(ngram='0,73_NUM', year=1972, match_count=232, volume_count=125)
Record(ngram='0,73_NUM', year=1973, match_count=265, volume_count=153)
Record(ngram='0,73_NUM', year=1974, match_count=262, volume_count=142)
Record(ngram='0,73_NUM', year=1975, match_count=322, volume_count=168)
Record(ngram='0,73_NUM', year=1976, match_count=285, volume_count=141)
Record(ngram='0,73_NUM', year=1977, match_count=273, volume_count=139)
Record(ngram='0,73_NUM', year=1978, match_count=261, volume_count=146)
Record(ngram='0,73_NUM', year=1979, match_count=329, volume_count=166)
Record(ngram='0,73_NUM', year=1980, match_count=329, volume_count=151)
Record(ngram='0,73_NUM', year=1981, match_count=301, volume_count=158)
Record(ngram='0,73_NUM', year=1982, match_count=339, volume_count=171)
Record(ngram='0,73_NUM', year=1983, match_count=369, volume_count=188)
Record(ngram='0,73_NUM', year=1984, match_count=288, volume_count=147)
Record(ngram='0,73_NUM', year=1985, match_count=363, volume_count=177)
Record(ngram='0,73_NUM', year=1986, match_count=305, volume_count=171)
Record(ngram='0,73_NUM', year=1987, match_count=347, volume_count=187)
Record(ngram='0,73_NUM', year=1988, match_count=341, volume_count=180)
Record(ngram='0,73_NUM', year=1989, match_count=350, volume_count=192)
Record(ngram='0,73_NUM', year=1990, match_count=381, volume_count=200)
Record(ngram='0,73_NUM', year=1991, match_count=399, volume_count=218)
Record(ngram='0,73_NUM', year=1992, match_count=405, volume_count=223)
Record(ngram='0,73_NUM', year=1993, match_count=332, volume_count=173)
Record(ngram='0,73_NUM', year=1994, match_count=395, volume_count=219)
Record(ngram='0,73_NUM', year=1995, match_count=431, volume_count=240)
Record(ngram='0,73_NUM', year=1996, match_count=498, volume_count=250)
Record(ngram='0,73_NUM', year=1997, match_count=501, volume_count=240)
Record(ngram='0,73_NUM', year=1998, match_count=602, volume_count=280)
Record(ngram='0,73_NUM', year=1999, match_count=578, volume_count=265)
Record(ngram='0,73_NUM', year=2000, match_count=619, volume_count=289)
Record(ngram='0,73_NUM', year=2001, match_count=617, volume_count=304)
Record(ngram='0,73_NUM', year=2002, match_count=564, volume_count=264)
Record(ngram='0,73_NUM', year=2003, match_count=540, volume_count=308)
Record(ngram='0,73_NUM', year=2004, match_count=620, volume_count=316)
Record(ngram='0,73_NUM', year=2005, match_count=903, volume_count=376)
Record(ngram='0,73_NUM', year=2006, match_count=774, volume_count=358)
Record(ngram='0,73_NUM', year=2007, match_count=507, volume_count=253)
Record(ngram='0,73_NUM', year=2008, match_count=487, volume_count=230)
Record(ngram='0,73_NUM', year=2009, match_count=220, volume_count=123)
Record(ngram='0,75-1,00', year=1948, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1949, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1950, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1951, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1952, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1954, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1956, match_count=5, volume_count=5)
Record(ngram='0,75-1,00', year=1957, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1965, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1966, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1967, match_count=3, volume_count=3)
Record(ngram='0,75-1,00', year=1970, match_count=3, volume_count=3)
Record(ngram='0,75-1,00', year=1973, match_count=52, volume_count=3)
Record(ngram='0,75-1,00', year=1974, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1975, match_count=7, volume_count=2)
Record(ngram='0,75-1,00', year=1976, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1978, match_count=7, volume_count=1)
Record(ngram='0,75-1,00', year=1979, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1981, match_count=2, volume_count=1)
Record(ngram='0,75-1,00', year=1983, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1984, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1985, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1988, match_count=42, volume_count=4)
Record(ngram='0,75-1,00', year=1989, match_count=4, volume_count=1)
Record(ngram='0,75-1,00', year=1990, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1991, match_count=5, volume_count=1)
Record(ngram='0,75-1,00', year=1992, match_count=2, volume_count=2)
Record(ngram='0,75-1,00', year=1994, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1995, match_count=3, volume_count=2)
Record(ngram='0,75-1,00', year=1998, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=1999, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=2002, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=2003, match_count=4, volume_count=3)
Record(ngram='0,75-1,00', year=2004, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=2005, match_count=1, volume_count=1)
Record(ngram='0,75-1,00', year=2006, match_count=3, volume_count=1)
Record(ngram='0,75-1,00', year=2008, match_count=2, volume_count=2)
Record(ngram='0,863', year=1834, match_count=1, volume_count=1)
Record(ngram='0,863', year=1847, match_count=2, volume_count=2)
Record(ngram='0,863', year=1853, match_count=1, volume_count=1)
Record(ngram='0,863', year=1854, match_count=5, volume_count=5)
Record(ngram='0,863', year=1859, match_count=1, volume_count=1)
Record(ngram='0,863', year=1861, match_count=3, volume_count=3)
Record(ngram='0,863', year=1863, match_count=3, volume_count=3)
Record(ngram='0,863', year=1867, match_count=4, volume_count=1)
Record(ngram='0,863', year=1869, match_count=1, volume_count=1)
Record(ngram='0,863', year=1877, match_count=1, volume_count=1)
Record(ngram='0,863', year=1878, match_count=1, volume_count=1)
Record(ngram='0,863', year=1890, match_count=1, volume_count=1)
Record(ngram='0,863', year=1893, match_count=1, volume_count=1)
Record(ngram='0,863', year=1902, match_count=1, volume_count=1)
Record(ngram='0,863', year=1908, match_count=1, volume_count=1)
Record(ngram='0,863', year=1909, match_count=1, volume_count=1)
Record(ngram='0,863', year=1915, match_count=1, volume_count=1)
Record(ngram='0,863', year=1916, match_count=4, volume_count=4)
Record(ngram='0,863', year=1917, match_count=1, volume_count=1)
Record(ngram='0,863', year=1922, match_count=4, volume_count=3)
Record(ngram='0,863', year=1926, match_count=2, volume_count=1)
Record(ngram='0,863', year=1927, match_count=14, volume_count=3)
Record(ngram='0,863', year=1928, match_count=6, volume_count=6)
Record(ngram='0,863', year=1930, match_count=3, volume_count=3)
Record(ngram='0,863', year=1932, match_count=1, volume_count=1)
Record(ngram='0,863', year=1934, match_count=3, volume_count=1)
Record(ngram='0,863', year=1935, match_count=1, volume_count=1)
Record(ngram='0,863', year=1936, match_count=1, volume_count=1)
Record(ngram='0,863', year=1938, match_count=1, volume_count=1)
Record(ngram='0,863', year=1939, match_count=2, volume_count=2)
Record(ngram='0,863', year=1940, match_count=3, volume_count=3)
Record(ngram='0,863', year=1942, match_count=6, volume_count=3)
Record(ngram='0,863', year=1944, match_count=3, volume_count=3)
Record(ngram='0,863', year=1946, match_count=2, volume_count=2)
Record(ngram='0,863', year=1947, match_count=1, volume_count=1)
Record(ngram='0,863', year=1949, match_count=4, volume_count=3)
Record(ngram='0,863', year=1950, match_count=1, volume_count=1)
Record(ngram='0,863', year=1951, match_count=2, volume_count=2)
Record(ngram='0,863', year=1952, match_count=2, volume_count=2)
Record(ngram='0,863', year=1953, match_count=2, volume_count=2)
Record(ngram='0,863', year=1954, match_count=2, volume_count=2)
Record(ngram='0,863', year=1956, match_count=4, volume_count=4)
Record(ngram='0,863', year=1957, match_count=3, volume_count=2)
Record(ngram='0,863', year=1959, match_count=16, volume_count=6)
Record(ngram='0,863', year=1960, match_count=1, volume_count=1)
Record(ngram='0,863', year=1961, match_count=6, volume_count=3)
Record(ngram='0,863', year=1962, match_count=5, volume_count=5)
Record(ngram='0,863', year=1963, match_count=1, volume_count=1)
Record(ngram='0,863', year=1964, match_count=8, volume_count=8)
Record(ngram='0,863', year=1965, match_count=7, volume_count=7)
Record(ngram='0,863', year=1966, match_count=2, volume_count=2)
Record(ngram='0,863', year=1967, match_count=5, volume_count=5)
Record(ngram='0,863', year=1968, match_count=5, volume_count=5)
Record(ngram='0,863', year=1969, match_count=2, volume_count=2)
Record(ngram='0,863', year=1970, match_count=5, volume_count=3)
Record(ngram='0,863', year=1971, match_count=5, volume_count=5)
Record(ngram='0,863', year=1973, match_count=13, volume_count=10)
Record(ngram='0,863', year=1974, match_count=10, volume_count=7)
Record(ngram='0,863', year=1975, match_count=7, volume_count=6)
Record(ngram='0,863', year=1976, match_count=12, volume_count=7)
Record(ngram='0,863', year=1977, match_count=3, volume_count=3)
Record(ngram='0,863', year=1978, match_count=7, volume_count=6)
Record(ngram='0,863', year=1979, match_count=7, volume_count=7)
Record(ngram='0,863', year=1980, match_count=5, volume_count=5)
Record(ngram='0,863', year=1981, match_count=3, volume_count=3)
Record(ngram='0,863', year=1982, match_count=5, volume_count=5)
Record(ngram='0,863', year=1983, match_count=6, volume_count=5)
Record(ngram='0,863', year=1984, match_count=7, volume_count=7)
Record(ngram='0,863', year=1985, match_count=4, volume_count=4)
Record(ngram='0,863', year=1986, match_count=8, volume_count=8)
Record(ngram='0,863', year=1987, match_count=3, volume_count=3)
Record(ngram='0,863', year=1988, match_count=9, volume_count=6)
Record(ngram='0,863', year=1989, match_count=1, volume_count=1)
Record(ngram='0,863', year=1990, match_count=8, volume_count=7)
Record(ngram='0,863', year=1991, match_count=7, volume_count=6)
Record(ngram='0,863', year=1992, match_count=13, volume_count=13)
Record(ngram='0,863', year=1993, match_count=9, volume_count=8)
Record(ngram='0,863', year=1994, match_count=18, volume_count=16)
Record(ngram='0,863', year=1995, match_count=9, volume_count=7)
Record(ngram='0,863', year=1996, match_count=8, volume_count=7)
Record(ngram='0,863', year=1997, match_count=5, volume_count=4)
Record(ngram='0,863', year=1998, match_count=13, volume_count=11)
Record(ngram='0,863', year=1999, match_count=3, volume_count=3)
Record(ngram='0,863', year=2000, match_count=20, volume_count=14)
Record(ngram='0,863', year=2001, match_count=35, volume_count=23)
Record(ngram='0,863', year=2002, match_count=23, volume_count=17)
Record(ngram='0,863', year=2003, match_count=18, volume_count=12)
Record(ngram='0,863', year=2004, match_count=13, volume_count=12)
Record(ngram='0,863', year=2005, match_count=25, volume_count=20)
Record(ngram='0,863', year=2006, match_count=23, volume_count=19)
Record(ngram='0,863', year=2007, match_count=16, volume_count=13)
Record(ngram='0,863', year=2008, match_count=29, volume_count=19)
Record(ngram='0,863', year=2009, match_count=20, volume_count=11)
Record(ngram='0,9688_NUM', year=1834, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1839, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=1851, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1909, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1944, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1945, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1973, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1975, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1977, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1982, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=1986, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=1987, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1991, match_count=5, volume_count=5)
Record(ngram='0,9688_NUM', year=1993, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1994, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1995, match_count=2, volume_count=1)
Record(ngram='0,9688_NUM', year=1996, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=1998, match_count=4, volume_count=4)
Record(ngram='0,9688_NUM', year=1999, match_count=1, volume_count=1)
Record(ngram='0,9688_NUM', year=2001, match_count=6, volume_count=6)
Record(ngram='0,9688_NUM', year=2003, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=2005, match_count=4, volume_count=4)
Record(ngram='0,9688_NUM', year=2006, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=2007, match_count=2, volume_count=2)
Record(ngram='0,9688_NUM', year=2009, match_count=4, volume_count=4)
Record(ngram='0-1800', year=1912, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1941, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1960, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1964, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1968, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1971, match_count=1, volume_count=1)
Record(ngram='0-1800', year=1975, match_count=2, volume_count=2)
Record(ngram='0-1800', year=1977, match_count=2, volume_count=1)
Record(ngram='0-1800', year=1979, match_count=4, volume_count=3)

KeyboardInterrupt: ignored

In [ ]:
ngrams, vocab = nltk.lm.preprocessing.padded_everygram_pipeline(n, [ngram for ngram, freq in ngram_freqs for _ in range(freq)])

alpha = 0.01
model = Lidstone(order=n, gamma=alpha, vocabulary=nltk.lm.Vocabulary(vocab, unk_cutoff=1))


model.fit(ngrams)

In [ ]:
import pickle
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("model.pkl", "rb") as f:
    loaded_model = pickle.load(f)